<?php declare(strict_types=1);

namespace App\Model\Hearing;

use JakubBoucek\Hydrator\Entity;


/**
 * One sighting of a hearing in one source, kept verbatim: `observedAt` is the
 * source's own "valid as of" stamp (infoJednani `platneK`), `rawJson` the
 * source event exactly as received. Hearings are merged from these.
 *
 * `rawJson` stays a string on purpose - raw source payloads are snapshots, not
 * typed data (see docs/entity-refactoring.md). The `room_key` column is
 * generated by the database and therefore has no property here.
 */
class HearingObservation implements Entity
{
    public int $id;
    public int $hearingId;
    public ObservationSource $source;
    public \DateTimeImmutable $observedAt;
    /** Room this observation saw the hearing in - part of the dedup key. */
    public ?string $room;
    public ?string $rawJson;
    public \DateTimeImmutable $createdAt;
}
