-- Codelists for the spisovka parser tool: courts (with derived parent and
-- level), court prefixes (ISIR codes -> infosoud codes), registries (seeded
-- from the MSP list, cross-checked with the infosoud API lov) and senate
-- rules (empty, filled by admin over time).

CREATE TABLE `court`
(
    `kod`        VARCHAR(10)  NOT NULL,
    `name`       VARCHAR(100) NOT NULL,
    `level`      VARCHAR(3)   NOT NULL,
    `parent_kod` VARCHAR(10)  NULL DEFAULT NULL,
    PRIMARY KEY (`kod`),
    KEY `ix_court_level` (`level`),
    CONSTRAINT `fk_court_parent` FOREIGN KEY (`parent_kod`) REFERENCES `court` (`kod`),
    CONSTRAINT `chk_court_level` CHECK (`level` IN ('os', 'ks', 'vs', 'ns', 'nss'))
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `court_prefix`
(
    `prefix`    VARCHAR(10)  NOT NULL,
    `court_kod` VARCHAR(10)  NOT NULL,
    `note`      VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`prefix`),
    CONSTRAINT `fk_court_prefix_court` FOREIGN KEY (`court_kod`) REFERENCES `court` (`kod`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `registry`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code`        VARCHAR(10)  NOT NULL,
    `code_norm`   VARCHAR(10)  NOT NULL,
    `court_level` VARCHAR(3)   NULL DEFAULT NULL,
    `agenda`      VARCHAR(150) NULL DEFAULT NULL,
    `description` TEXT         NULL DEFAULT NULL,
    `note`        VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_registry_norm_level` (`code_norm`, `court_level`),
    KEY `ix_registry_norm` (`code_norm`),
    CONSTRAINT `chk_registry_level` CHECK (`court_level` IN ('os', 'ks', 'vs', 'ns', 'nss'))
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;

CREATE TABLE `senate_rule`
(
    `id`            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `registry_norm` VARCHAR(10)  NOT NULL,
    `senate`        INT UNSIGNED NOT NULL,
    `court_kod`     VARCHAR(10)  NOT NULL,
    `note`          VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_senate_rule` (`registry_norm`, `senate`),
    CONSTRAINT `fk_senate_rule_court` FOREIGN KEY (`court_kod`) REFERENCES `court` (`kod`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_520_ci;

INSERT INTO `court` (`kod`, `name`, `level`, `parent_kod`) VALUES
    ('KSJIMBM', 'Krajský soud Brno', 'ks', NULL),
    ('KSJICCB', 'Krajský soud České Budějovice', 'ks', NULL),
    ('KSVYCHK', 'Krajský soud Hradec Králové', 'ks', NULL),
    ('KSSEMOS', 'Krajský soud Ostrava', 'ks', NULL),
    ('KSZPCPM', 'Krajský soud Plzeň', 'ks', NULL),
    ('KSSTCAB', 'Krajský soud Praha', 'ks', NULL),
    ('KSSCEUL', 'Krajský soud Ústí nad Labem', 'ks', NULL),
    ('MSPHAAB', 'Městský soud Praha', 'ks', NULL),
    ('VSSEMOL', 'Vrchní soud Olomouc', 'vs', NULL),
    ('VSPHAAB', 'Vrchní soud Praha', 'vs', NULL),
    ('OSJIMBM', 'Městský soud Brno', 'os', 'KSJIMBM'),
    ('OSPHA01', 'Obvodní soud Praha 1', 'os', 'MSPHAAB'),
    ('OSPHA10', 'Obvodní soud Praha 10', 'os', 'MSPHAAB'),
    ('OSPHA02', 'Obvodní soud Praha 2', 'os', 'MSPHAAB'),
    ('OSPHA03', 'Obvodní soud Praha 3', 'os', 'MSPHAAB'),
    ('OSPHA04', 'Obvodní soud Praha 4', 'os', 'MSPHAAB'),
    ('OSPHA05', 'Obvodní soud Praha 5', 'os', 'MSPHAAB'),
    ('OSPHA06', 'Obvodní soud Praha 6', 'os', 'MSPHAAB'),
    ('OSPHA07', 'Obvodní soud Praha 7', 'os', 'MSPHAAB'),
    ('OSPHA08', 'Obvodní soud Praha 8', 'os', 'MSPHAAB'),
    ('OSPHA09', 'Obvodní soud Praha 9', 'os', 'MSPHAAB'),
    ('OSSTCBN', 'Okresní soud Benešov', 'os', 'KSSTCAB'),
    ('OSSTCBE', 'Okresní soud Beroun', 'os', 'KSSTCAB'),
    ('OSJIMBK', 'Okresní soud Blansko', 'os', 'KSJIMBM'),
    ('OSJIMBO', 'Okresní soud Brno-venkov', 'os', 'KSJIMBM'),
    ('OSSEMBR', 'Okresní soud Bruntál', 'os', 'KSSEMOS'),
    ('OSJIMBV', 'Okresní soud Břeclav', 'os', 'KSJIMBM'),
    ('OSZPCCH', 'Okresní soud Cheb', 'os', 'KSZPCPM'),
    ('OSSCECV', 'Okresní soud Chomutov', 'os', 'KSSCEUL'),
    ('OSVYCCR', 'Okresní soud Chrudim', 'os', 'KSVYCHK'),
    ('OSZPCDO', 'Okresní soud Domažlice', 'os', 'KSZPCPM'),
    ('OSSCEDC', 'Okresní soud Děčín', 'os', 'KSSCEUL'),
    ('OSSEMFM', 'Okresní soud Frýdek-Místek', 'os', 'KSSEMOS'),
    ('OSVYCHB', 'Okresní soud Havlíčkův Brod', 'os', 'KSVYCHK'),
    ('OSJIMHO', 'Okresní soud Hodonín', 'os', 'KSJIMBM'),
    ('OSVYCHK', 'Okresní soud Hradec Králové', 'os', 'KSVYCHK'),
    ('OSSCEJN', 'Okresní soud Jablonec nad Nisou', 'os', 'KSSCEUL'),
    ('OSSEMJE', 'Okresní soud Jeseník', 'os', 'KSSEMOS'),
    ('OSJIMJI', 'Okresní soud Jihlava', 'os', 'KSJIMBM'),
    ('OSJICJH', 'Okresní soud Jindřichův Hradec', 'os', 'KSJICCB'),
    ('OSVYCJC', 'Okresní soud Jičín', 'os', 'KSVYCHK'),
    ('OSZPCKV', 'Okresní soud Karlovy Vary', 'os', 'KSZPCPM'),
    ('OSSEMKA', 'Okresní soud Karviná', 'os', 'KSSEMOS'),
    ('OSSTCKL', 'Okresní soud Kladno', 'os', 'KSSTCAB'),
    ('OSZPCKT', 'Okresní soud Klatovy', 'os', 'KSZPCPM'),
    ('OSSTCKO', 'Okresní soud Kolín', 'os', 'KSSTCAB'),
    ('OSJIMKM', 'Okresní soud Kroměříž', 'os', 'KSJIMBM'),
    ('OSSTCKH', 'Okresní soud Kutná Hora', 'os', 'KSSTCAB'),
    ('OSSCELB', 'Okresní soud Liberec', 'os', 'KSSCEUL'),
    ('OSSCELT', 'Okresní soud Litoměřice', 'os', 'KSSCEUL'),
    ('OSSCELN', 'Okresní soud Louny', 'os', 'KSSCEUL'),
    ('OSSTCMB', 'Okresní soud Mladá Boleslav', 'os', 'KSSTCAB'),
    ('OSSCEMO', 'Okresní soud Most', 'os', 'KSSCEUL'),
    ('OSSTCME', 'Okresní soud Mělník', 'os', 'KSSTCAB'),
    ('OSSEMNJ', 'Okresní soud Nový Jičín', 'os', 'KSSEMOS'),
    ('OSSTCNB', 'Okresní soud Nymburk', 'os', 'KSSTCAB'),
    ('OSVYCNA', 'Okresní soud Náchod', 'os', 'KSVYCHK'),
    ('OSSEMOC', 'Okresní soud Olomouc', 'os', 'KSSEMOS'),
    ('OSSEMOP', 'Okresní soud Opava', 'os', 'KSSEMOS'),
    ('OSSEMOS', 'Okresní soud Ostrava', 'os', 'KSSEMOS'),
    ('OSVYCPA', 'Okresní soud Pardubice', 'os', 'KSVYCHK'),
    ('OSJICPE', 'Okresní soud Pelhřimov', 'os', 'KSJICCB'),
    ('OSZPCPM', 'Okresní soud Plzeň-Město', 'os', 'KSZPCPM'),
    ('OSZPCPJ', 'Okresní soud Plzeň-jih', 'os', 'KSZPCPM'),
    ('OSZPCPS', 'Okresní soud Plzeň-sever', 'os', 'KSZPCPM'),
    ('OSJICPT', 'Okresní soud Prachatice', 'os', 'KSJICCB'),
    ('OSSTCPY', 'Okresní soud Praha-Východ', 'os', 'KSSTCAB'),
    ('OSSTCPZ', 'Okresní soud Praha-Západ', 'os', 'KSSTCAB'),
    ('OSJIMPV', 'Okresní soud Prostějov', 'os', 'KSJIMBM'),
    ('OSJICPI', 'Okresní soud Písek', 'os', 'KSJICCB'),
    ('OSSEMPR', 'Okresní soud Přerov', 'os', 'KSSEMOS'),
    ('OSSTCPB', 'Okresní soud Příbram', 'os', 'KSSTCAB'),
    ('OSSTCRA', 'Okresní soud Rakovník', 'os', 'KSSTCAB'),
    ('OSZPCRO', 'Okresní soud Rokycany', 'os', 'KSZPCPM'),
    ('OSVYCRK', 'Okresní soud Rychnov nad Kněžnou', 'os', 'KSVYCHK'),
    ('OSVYCSM', 'Okresní soud Semily', 'os', 'KSVYCHK'),
    ('OSZPCSO', 'Okresní soud Sokolov', 'os', 'KSZPCPM'),
    ('OSJICST', 'Okresní soud Strakonice', 'os', 'KSJICCB'),
    ('OSVYCSY', 'Okresní soud Svitavy', 'os', 'KSVYCHK'),
    ('OSZPCTC', 'Okresní soud Tachov', 'os', 'KSZPCPM'),
    ('OSSCETP', 'Okresní soud Teplice', 'os', 'KSSCEUL'),
    ('OSVYCTU', 'Okresní soud Trutnov', 'os', 'KSVYCHK'),
    ('OSJICTA', 'Okresní soud Tábor', 'os', 'KSJICCB'),
    ('OSJIMTR', 'Okresní soud Třebíč', 'os', 'KSJIMBM'),
    ('OSJIMUH', 'Okresní soud Uherské Hradiště', 'os', 'KSJIMBM'),
    ('OSSEMVS', 'Okresní soud Vsetín', 'os', 'KSSEMOS'),
    ('OSJIMVY', 'Okresní soud Vyškov', 'os', 'KSJIMBM'),
    ('OSJIMZL', 'Okresní soud Zlín', 'os', 'KSJIMBM'),
    ('OSJIMZN', 'Okresní soud Znojmo', 'os', 'KSJIMBM'),
    ('OSSCEUL', 'Okresní soud Ústí nad Labem', 'os', 'KSSCEUL'),
    ('OSVYCUO', 'Okresní soud Ústí nad Orlicí', 'os', 'KSVYCHK'),
    ('OSSCECL', 'Okresní soud Česká Lípa', 'os', 'KSSCEUL'),
    ('OSJICCB', 'Okresní soud České Budějovice', 'os', 'KSJICCB'),
    ('OSJICCK', 'Okresní soud Český Krumlov', 'os', 'KSJICCB'),
    ('OSSEMSU', 'Okresní soud Šumperk', 'os', 'KSSEMOS'),
    ('OSJIMZR', 'Okresní soud Žďár nad Sázavou', 'os', 'KSJIMBM'),
    ('NS', 'Nejvyšší soud', 'ns', NULL),
    ('NSS', 'Nejvyšší správní soud', 'nss', NULL);

INSERT INTO `court_prefix` (`prefix`, `court_kod`, `note`) VALUES
    ('MSPH', 'MSPHAAB', 'ISIR: Městský soud Praha'),
    ('KSPH', 'KSSTCAB', 'ISIR: Krajský soud Praha'),
    ('KSCB', 'KSJICCB', 'ISIR: Krajský soud České Budějovice'),
    ('KSPL', 'KSZPCPM', 'ISIR: Krajský soud Plzeň'),
    ('KSUL', 'KSSCEUL', 'ISIR: Krajský soud Ústí nad Labem'),
    ('KSLB', 'KSSCEUL', 'ISIR: KS Ústí nad Labem – pobočka Liberec'),
    ('KSHK', 'KSVYCHK', 'ISIR: Krajský soud Hradec Králové'),
    ('KSPA', 'KSVYCHK', 'ISIR: KS Hradec Králové – pobočka Pardubice'),
    ('KSBR', 'KSJIMBM', 'ISIR: Krajský soud Brno'),
    ('KSOS', 'KSSEMOS', 'ISIR: Krajský soud Ostrava'),
    ('KSOL', 'KSSEMOS', 'ISIR: KS Ostrava – pobočka Olomouc'),
    ('VSPH', 'VSPHAAB', 'ISIR: Vrchní soud Praha'),
    ('VSOL', 'VSSEMOL', 'ISIR: Vrchní soud Olomouc'),
    ('NS', 'NS', 'Nejvyšší soud'),
    ('NSS', 'NSS', 'Nejvyšší správní soud');

INSERT INTO `registry` (`code`, `code_norm`, `court_level`, `agenda`, `description`, `note`) VALUES
    ('T', 'T', 'os', 'Trestní agenda', 'rejstřík pro věci trestní', NULL),
    ('Tm', 'TM', 'os', 'Trestní agenda', 'rejstřík pro trestní věci mladistvých', NULL),
    ('Nt', 'NT', 'os', 'Trestní agenda', 'rejstřík pro věci přípravného řízení a pro všeobecné věci trestní', NULL),
    ('Ntm', 'NTM', 'os', 'Trestní agenda', 'rejstřík pro věci přípravného řízení a pro všeobecné věci trestní mladistvých', NULL),
    ('PP', 'PP', 'os', 'Trestní agenda', 'rejstřík pro věci řízení o podmíněném propuštění', NULL),
    ('Dt', 'DT', 'os', 'Trestní agenda', 'rejstřík pro věci výkonu zabezpečovací detence', NULL),
    ('Dtm', 'DTM', 'os', 'Trestní agenda', 'rejstřík pro věci výkonu zabezpečovací detence mladistvých', NULL),
    ('Td', 'TD', 'os', 'Trestní agenda', 'rejstřík pro dožádání ve věcech trestních', NULL),
    ('C', 'C', 'os', 'Občanskoprávní agenda', 'rejstřík pro věci občanskoprávní, včetně návrhů na vydání platebního rozkazu', NULL),
    ('EPR', 'EPR', 'os', 'Občanskoprávní agenda', 'rejstřík pro elektronické rozkazní řízení', NULL),
    ('EVC', 'EVC', 'os', 'Občanskoprávní agenda', 'rejstřík pro návrhy na vydání evropského platebního rozkazu', NULL),
    ('EC', 'EC', 'os', 'Občanskoprávní agenda', 'rejstřík pro návrhy na vydání elektronického platebního rozkazu', 'ukončen pro nové věci'),
    ('Ro', 'RO', 'os', 'Občanskoprávní agenda', 'rejstřík pro věci rozkazního řízení', 'ukončen pro nové věci'),
    ('ERo', 'ERO', 'os', 'Občanskoprávní agenda', 'rejstřík pro věci rozkazního řízení', 'ukončen pro nové věci'),
    ('P a Nc', 'P A NC', 'os', 'Opatrovnická agenda', 'rejstřík pro věci podpůrných opatření při narušení schopnosti zletilého právně jednat, nezvěstnosti, určování rodičovství, návrhů na uzavření manželství, péče o nezletilé děti atd.', NULL),
    ('Nc', 'NC', 'os', 'Opatrovnická agenda', 'rejstřík pro věci poručenské a opatrovnické, osvojení dětí a určení otcovství', NULL),
    ('P', 'P', 'os', 'Opatrovnická agenda', 'rejstřík pro opatrovnické věci osob vyžadujících trvalejší péči', NULL),
    ('L', 'L', 'os', 'Opatrovnická agenda', 'rejstřík pro věci detenčního řízení', NULL),
    ('E', 'E', 'os', 'Exekuční agenda', 'rejstřík pro věci týkající se výkonu rozhodnutí dle Občanského soudního řádu', NULL),
    ('EXE', 'EXE', 'os', 'Exekuční agenda', 'rejstřík pro věci exekuční', NULL),
    ('D', 'D', 'os', 'Dědická agenda', 'rejstřík pro věci pozůstalostní', NULL),
    ('U', 'U', 'os', 'Dědická agenda', 'rejstřík pro věci řízení o umoření listin', NULL),
    ('Sd', 'SD', 'os', 'Dědická agenda', 'rejstřík pro věci týkající se úschov přijímaných soudem', NULL),
    ('Cd', 'CD', 'os', 'Další agenda', 'rejstřík pro dožádání ve věcech civilních', NULL),
    ('Rod', 'ROD', 'os', 'Další agenda', 'rejstřík pro věci dětí mladších 15 let', NULL),
    ('T', 'T', 'ks', 'Trestní agenda', 'rejstřík pro věci trestní', NULL),
    ('Tm', 'TM', 'ks', 'Trestní agenda', 'rejstřík pro trestní věci mladistvých', NULL),
    ('To', 'TO', 'ks', 'Trestní agenda', 'rejstřík pro věci řízení o opravných prostředcích', NULL),
    ('Tmo', 'TMO', 'ks', 'Trestní agenda', 'rejstřík pro věci odvolacího řízení a řízení o stížnostech v trestních věcech mladistvých', NULL),
    ('Nt', 'NT', 'ks', 'Trestní agenda', 'rejstřík pro všeobecné věci trestní', NULL),
    ('Ntm', 'NTM', 'ks', 'Trestní agenda', 'rejstřík pro všeobecné věci trestní mladistvých', NULL),
    ('C', 'C', 'ks', 'Občanskoprávní agenda', 'rejstřík pro věci občanskoprávní, včetně návrhů na vydání platebního rozkazu', NULL),
    ('Co', 'CO', 'ks', 'Občanskoprávní agenda', 'rejstřík pro věci odvolacího řízení ve věcech občanskoprávních', NULL),
    ('EC', 'EC', 'ks', 'Občanskoprávní agenda', 'rejstřík pro návrhy na vydání elektronického platebního rozkazu v občanskoprávních věcech', 'věci z EPR'),
    ('EPR', 'EPR', 'ks', 'Občanskoprávní agenda', 'rejstřík pro elektronické platební rozkazy', NULL),
    ('Nc', 'NC', 'ks', 'Občanskoprávní agenda', 'rejstřík pro všeobecné věci civilní', NULL),
    ('Cm', 'CM', 'ks', 'Obchodní agenda', 'rejstřík pro spory mezi podnikateli vyplývající z podnikatelské činnosti a další věci upravené zákonem o obchodních korporacích (obchodní věci)', NULL),
    ('ECm', 'ECM', 'ks', 'Obchodní agenda', 'rejstřík pro návrhy na vydání elektronického platebního rozkazu', 'věci z EPR'),
    ('EVCm', 'EVCM', 'ks', 'Obchodní agenda', 'rejstřík pro návrhy na vydání evropského platebního rozkazu', NULL),
    ('F', 'F', 'ks', 'Obchodní agenda', 'všeobecný rejstřík pro věci veřejných rejstříků FO a PO', NULL),
    ('ICm', 'ICM', 'ks', 'Obchodní agenda', 'rejstřík pro incidenční spory', NULL),
    ('INS', 'INS', 'ks', 'Obchodní agenda', 'rejstřík pro insolvenční návrhy a návrhy na moratorium před podáním insolvenčního návrhu', NULL),
    ('K', 'K', 'ks', 'Obchodní agenda', 'rejstřík pro konkursní řízení dle zákona o konkursu a vyrovnání', 'ukončen pro nové věci'),
    ('Kv', 'KV', 'ks', 'Obchodní agenda', 'rejstřík pro věci vyrovnacího řízení dle zákona o konkursu a vyrovnání', 'ukončen pro nové věci'),
    ('Ro', 'RO', 'ks', 'Obchodní agenda', 'rejstřík pro návrhy na vydání platebního rozkazu', 'ukončen pro nové věci'),
    ('Sm', 'SM', 'ks', 'Obchodní agenda', 'rejstřík pro návrhy na vydání směnečného/šekového platebního rozkazu', 'ukončen pro nové věci'),
    ('A', 'A', 'ks', 'Agenda správního soudnictví', 'rejstřík pro ostatní věci správního soudnictví, včetně věcí volebních a místního a krajského referenda, žaloby proti nečinnosti správního orgánu a žaloby na ochranu před nezákonným zásahem, pokynem nebo donucením správního orgánu', NULL),
    ('Ad', 'AD', 'ks', 'Agenda správního soudnictví', 'rejstřík pro věci sociální správy, zájmové a profesní samosprávy a služebních poměrů', NULL),
    ('Af', 'AF', 'ks', 'Agenda správního soudnictví', 'rejstřík pro věci finanční správy', NULL),
    ('Az', 'AZ', 'ks', 'Agenda správního soudnictví', 'rejstřík pro návrhy ve věcech mezinárodní ochrany', NULL),
    ('Ca', 'CA', 'ks', 'Agenda správního soudnictví', 'rejstřík pro věci správních žalob v ostatních věcech', 'ukončen pro nové věci'),
    ('Cad', 'CAD', 'ks', 'Agenda správního soudnictví', 'rejstřík pro věci správních žalob ve věcech sociálního zabezpečení', 'ukončen pro nové věci'),
    ('Na', 'NA', 'ks', 'Agenda správního soudnictví', 'rejstřík pro všeobecné věci správního soudnictví', NULL),
    ('Rodo', 'RODO', 'ks', 'Další agenda', 'rejstřík pro věci odvolacího řízení ve věcech dětí mladších 15 let', NULL),
    ('UL', 'UL', 'ks', 'Další agenda', 'rejstřík pro řízení o návrhu na určení lhůty', NULL),
    ('Dt', 'DT', 'vs', 'Trestní agenda', 'rejstřík pro věci trestní judikatury', NULL),
    ('Nt', 'NT', 'vs', 'Trestní agenda', 'rejstřík pro všeobecné věci trestní', NULL),
    ('Ntd', 'NTD', 'vs', 'Trestní agenda', 'rejstřík pro odnětí a přikázání věci (§ 25 tr. ř.) a rozhodování o příslušnosti (§ 24 tr. ř.) v trestních věcech', NULL),
    ('Ntm', 'NTM', 'vs', 'Trestní agenda', 'rejstřík pro všeobecné věci trestní mladistvých', NULL),
    ('Tmo', 'TMO', 'vs', 'Trestní agenda', 'rejstřík pro věci odvolacího řízení a řízení o stížnostech v trestních věcech mladistvých', NULL),
    ('To', 'TO', 'vs', 'Trestní agenda', 'rejstřík pro věci řízení o opravných prostředcích', NULL),
    ('Tpj', 'TPJ', 'vs', 'Trestní agenda', 'rejstřík pro věci místopředsedy trestního úseku soudu', NULL),
    ('Cmo', 'CMO', 'vs', 'Civilní agenda', 'rejstřík odvolacího řízení v obchodních věcech', NULL),
    ('Co', 'CO', 'vs', 'Civilní agenda', 'rejstřík odvolacího řízení ve věcech občanskoprávních', NULL),
    ('Cpj', 'CPJ', 'vs', 'Civilní agenda', 'rejstřík pro věci místopředsedy civilního úseku soudu', NULL),
    ('Dc', 'DC', 'vs', 'Civilní agenda', 'rejstřík pro věci dokumentace civilní judikatury', NULL),
    ('ICm', 'ICM', 'vs', 'Civilní agenda', 'rejstřík odvolacího řízení v incidenčních sporech a řízení o podjatosti, přikázání věci a příslušnosti v rámci incidenčního sporu', NULL),
    ('INS', 'INS', 'vs', 'Civilní agenda', 'rejstřík odvolacího řízení v insolvenčních věcech a řízení o podjatosti, přikázání věci a příslušnosti v insolvenčním řízení', NULL),
    ('Ko', 'KO', 'vs', 'Civilní agenda', 'rejstřík pro odvolací řízení ve věcech podle zákona o konkursu a vyrovnání', NULL),
    ('Nc', 'NC', 'vs', 'Civilní agenda', 'rejstřík pro všeobecné věci občanskoprávní, insolvenční, vyrovnací', NULL),
    ('Ncd', 'NCD', 'vs', 'Civilní agenda', 'rejstřík pro návrhy na přikázání věci jinému soudu v civilních věcech', NULL),
    ('Nco', 'NCO', 'vs', 'Civilní agenda', 'rejstřík pro rozhodování o vyloučení soudců v civilních věcech', NULL),
    ('Ncp', 'NCP', 'vs', 'Civilní agenda', 'rejstřík pro rozhodování o příslušnosti v civilních věcech', NULL),
    ('UL', 'UL', 'vs', 'Další agenda', 'rejstřík pro řízení o návrhu na určení lhůty', NULL),
    ('Cdo', 'CDO', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro řízení o dovolání ve věcech občanskoprávních a obchodních', NULL),
    ('Cul', 'CUL', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro návrhy na určení lhůty k provedení procesního úkonu v občanskoprávních a obchodních věcech', NULL),
    ('ICdo', 'ICDO', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro incidenční spory vyvolané v průběhu insolvenčního řízení', NULL),
    ('Ncu', 'NCU', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro návrhy na uznání cizozemských rozhodnutí', NULL),
    ('Nd', 'ND', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro spory o příslušnost mezi soudy', NULL),
    ('NSČR', 'NSČR', 'ns', 'Občanskoprávní a obchodní agenda', 'rejstřík pro věci předložené soudu k rozhodnutí v insolvenčním řízení', NULL),
    ('Pzo', 'PZO', 'ns', 'Trestní agenda', 'rejstřík pro věci návrhů na přezkum zákonnosti příkazu k odposlechu a záznamu telekomunikačního provozu a příkazu k zjištění údajů o telekomunikačním provozu', NULL),
    ('Tcu', 'TCU', 'ns', 'Trestní agenda', 'rejstřík pro návrhy na zaznamenání údajů o odsouzení občana České republiky cizozemským soudem do evidence Rejstříku trestů, návrhy na přezkum rozhodnutí o přípustnosti vydání do ciziny, návrhy na vynětí z pravomoci orgánů činných v trestním řízení', NULL),
    ('Td', 'TD', 'ns', 'Trestní agenda', 'rejstřík pro spory o příslušnost mezi soudy nižších stupňů, návrhy na odnětí a přikázání věci, stížnosti proti rozhodnutím o vyloučení soudce', NULL),
    ('Tdo', 'TDO', 'ns', 'Trestní agenda', 'rejstřík pro řízení o dovolání ve věcech trestních', NULL),
    ('Tul', 'TUL', 'ns', 'Trestní agenda', 'rejstřík pro návrhy na určení lhůty k provedení procesního úkonu', NULL),
    ('Tvo', 'TVO', 'ns', 'Trestní agenda', 'rejstřík pro stížnosti proti rozhodnutím vrchních soudů o prodloužení vazby a proti dalším rozhodnutím vrchních soudů, pokud rozhodovaly v postavení soudu prvního stupně', NULL),
    ('Tz', 'TZ', 'ns', 'Trestní agenda', 'rejstřík pro stížnosti pro porušení zákona v trestních věcech', NULL),
    ('Zp', 'ZP', 'ns', 'Trestní agenda', 'rejstřík pro věci, v nichž je podáno odvolání proti rozhodnutí Kárné komory Nejvyššího kontrolního úřadu', NULL),
    ('As', 'AS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech dále neuvedených', NULL),
    ('Ads', 'ADS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech důchodového pojištění, nemocenského pojištění, zdravotního pojištění, nemocenské péče v ozbrojených silách, uchazečů o zaměstnání a jejich hmotného zabezpečení podle předpisů o zaměstnanosti, sociální péče a státní sociální podpory, pojistného na sociální zabezpečení a příspěvku na státní politiku zaměstnanosti', NULL),
    ('Afs', 'AFS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech cel, daní, poplatků a ostatních daňových řízení, ve věcech týkajících se rozpočtových pravidel a dotací', NULL),
    ('Ans', 'ANS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech ochrany proti nečinnosti správního orgánu', 'ukončen pro nové věci'),
    ('Aos', 'AOS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech opatření obecné povahy jejichž přezkum je upraven § 13 zákona o mimořádných opatření při epidemii COVID-19 a o změně některých souvisejících zákonů', NULL),
    ('Aps', 'APS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech ochrany před nezákonným zásahem, pokynem nebo donucením správního orgánu', 'ukončen pro nové věci'),
    ('Ars', 'ARS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech krajského a místního referenda, ve věcech dohledu nad hospodařením politických stran a hnutí a ve věcech dohledu nad financováním volebních kampaní politických stran a hnutí', NULL),
    ('Azs', 'AZS', 'nss', 'Agenda kasačních stížností', 'rejstřík pro řízení o kasačních stížnostech ve věcech mezinárodní ochrany, zákona o dočasné ochraně cizinců a zákona o pobytu cizinců', NULL),
    ('Vol', 'VOL', 'nss', 'Agenda volebních věcí a věcí politických stran a hnutí (volební soudnictví)', 'rejstřík pro řízení ve věcech volebních podle § 88 a násl. s. ř. s.', NULL),
    ('Pst', 'PST', 'nss', 'Agenda volebních věcí a věcí politických stran a hnutí (volební soudnictví)', 'rejstřík pro řízení ve věcech politických stran a politických hnutí podle § 94 a násl. s. ř. s.', NULL),
    ('Obn', 'OBN', 'nss', 'Agenda volebních věcí a věcí politických stran a hnutí (volební soudnictví)', 'rejstřík pro rozhodování o obnově řízení ve věcech politických stran a politických hnutí', NULL),
    ('Nv', 'NV', 'nss', 'Agenda volebních věcí a věcí politických stran a hnutí (volební soudnictví)', 'rejstřík pro volební věci - ostatní věci', NULL),
    ('Kse', 'KSE', 'nss', 'Agenda kárného řízení (kárný soud)', 'rejstřík pro řízení ve věcech kárné odpovědnosti soudních exekutorů', NULL),
    ('Kss', 'KSS', 'nss', 'Agenda kárného řízení (kárný soud)', 'rejstřík pro řízení ve věcech kárné odpovědnosti soudců, nezpůsobilosti soudce', NULL),
    ('Ksz', 'KSZ', 'nss', 'Agenda kárného řízení (kárný soud)', 'rejstřík pro řízení ve věcech kárné odpovědnosti státních zástupců', NULL),
    ('Kseo', 'KSEO', 'nss', 'Agenda kárného řízení (kárný soud)', 'rejstřík pro řízení o odvolání proti rozhodnutí kárné komise Exekutorské komory České republiky', 'ukončen pro nové věci'),
    ('Nk', 'NK', 'nss', 'Agenda kárného řízení (kárný soud)', 'rejstřík pro řízení ve věcech kárné odpovědnosti – ostatní věci', NULL),
    ('Aprk', 'APRK', 'nss', 'Další agenda', 'rejstřík pro řízení o návrhu na určení lhůty k provedení procesního úkonu krajským soudem (§ 174a zákona o soudech a soudcích)', NULL),
    ('Aprn', 'APRN', 'nss', 'Další agenda', 'rejstřík pro řízení o návrhu na určení lhůty k provedení procesního úkonu NSS (§ 174a zákona o soudech a soudcích)', NULL),
    ('Komp', 'KOMP', 'nss', 'Další agenda', 'rejstřík pro řízení o kompetenčních sporech podle § 97 a násl. s. ř. s.', NULL),
    ('Konf', 'KONF', 'nss', 'Další agenda', 'rejstřík pro řízení ve věcech kompetenčních sporů podle § 2 z. č. 131/2002 Sb., o rozhodování některých kompetenčních sporů', NULL),
    ('Ao', 'AO', 'nss', 'Další agenda', 'rejstřík pro řízení o návrhu na zrušení opatření obecné povahy nebo jeho části', NULL),
    ('Na', 'NA', 'nss', 'Další agenda', 'rejstřík pro ostatní věci', NULL),
    ('Nad', 'NAD', 'nss', 'Další agenda', 'rejstřík pro řízení o postoupení věci podle § 7 odst. 5 s. ř. s.; přikázání věci podle § 9 s. ř. s.', NULL),
    ('Nao', 'NAO', 'nss', 'Další agenda', 'rejstřík pro rozhodování o vyloučení soudce pro podjatost podle § 8 odst. 3 s. ř. s.', NULL),
    ('Rs', 'RS', 'nss', 'Další agenda', 'věci rozhodované sedmičlenným a devítičlenným rozšířeným senátem', NULL),
    ('ODO', 'ODO', NULL, NULL, NULL, 'jen v infosoud API, chybí v MSP seznamu');
